### ISSUE TITLE
Blog ist down

### ISSUE THREAD

**Issue by homaxi** [NilsEckelt/nilseckelt.github.io#5]
Moin Nils,

dein Blog scheint aktuell down zu sein.

Viele Grüße
Stefan und Max :-)

**Comment by eckelt** [comment]
Funny. Ja, nicht nur der. Hab's repariert. Nach 15 Monaten endlich wieder Zeit für Hobbies. 😊

**Comment by eckelt** [comment]
Please look at https://ecke.lt for the main blog.
